source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'
use_frameworks!
inhibit_all_warnings!

workspace 'About'
project 'About'

target 'About' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for About
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'

end
